--- # Provisioning Ubuntu hosts for forge
- hosts: '{{ host }}'
  gather_facts: yes
  become: yes
  tasks:
    - name: Extend bash history
      lineinfile: dest=/etc/bash.bashrc  regexp="^HISTSIZE=" line="HISTSIZE=1000000" state=present
      tags:
        - tools
    - name: Setup new SSH port
      lineinfile:
        dest: "/etc/ssh/sshd_config"
        regexp: "^#Port"
        line: "Port 22225"  
      tags:
        - tools

    - name: Update apt-get repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
      
    - name: Upgrade all apt packages
      apt: upgrade=dist force_apt_get=yes

    - name: Restart sshd
      service:
        name: sshd
        state: restarted
